services:
  accounts:
    image: "joaovitormoraveis/study-microservice-accounts:0.0.1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - study-group

  loans:
    image: "joaovitormoraveis/study-microservice-loans:0.0.1"
    container_name: loans-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - study-group

  cards:
    image: "joaovitormoraveis/study-microservice-cards:0.0.1"
    container_name: cards-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - study-group

networks:
  study-group:
    driver: "bridge"
