server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/accounts
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: localhost
    post: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

build:
  version: "3.0"

accounts:
  message: "DEV - Welcome to Accounts API"
  contact-details:
    name: "Joao Vitor"
    email: "test@test.com"
  on-call-support:
    - (123) 456-7890
    - (098) 765-4321
